Refactored everything
tlm-solutions/windshield pull request #18
Opened 2022-12-24 20:04 UTC by MarcelCoding

2022-12-25 17:58 UTC, revol-xut requested changes

2022-12-25 17:58 UTC, revol-xut commented on src/_core/map/map.component.ts
> +  private readonly location0 = new Subject<Location>();
why is there location0 and location ?

2022-12-25 17:58 UTC, revol-xut commented on src/_core/map/map.component.ts
> +  public getVehicle(id: string): Vehicle<Geometry> | undefined {
why this undefined ?

2022-12-25 17:58 UTC, revol-xut commented on src/_core/ws.ts
> +  private readonly stream0 = new Subject<O>();
stream0 ?

2022-12-25 17:58 UTC, revol-xut commented on src/app/pages/region/region-map/region-map.component.ts
> +          console.log("new");
more verbose print perhaps

2022-12-25 17:58 UTC, revol-xut commented on src/app/pages/region/region-map/region-map.component.ts
> +  // concat(
what happens with this dead code ?

2022-12-25 17:59 UTC, revol-xut commented
More of questions for my understanding :D 

Thank you very much

2022-12-25 23:33 UTC, MarcelCoding commented on src/app/pages/region/region-map/region-map.component.ts
> +          console.log("new");
thats remaining debugging and should be removed, by bad

2022-12-25 23:34 UTC, MarcelCoding commented on src/app/pages/region/region-map/region-map.component.ts
> +  // concat(
This got replayed by the new implmentation or is remaining stuff from the interpolation, which is still missing in the new one.

2022-12-25 23:35 UTC, MarcelCoding commented on src/_core/map/map.component.ts
> +  private readonly location0 = new Subject<Location>();
location0 is the action (private) field that holds the data and location is a public view to the data. (different "access permissions")

2022-12-25 23:36 UTC, MarcelCoding commented on src/_core/map/map.component.ts
> +  public getVehicle(id: string): Vehicle<Geometry> | undefined {
if the id could not be found in the provided data it is unknown and will be displayed as a car and not a tram or bus.

2022-12-25 23:36 UTC, MarcelCoding commented on src/_core/ws.ts
> +  private readonly stream0 = new Subject<O>();
the is a public field `stream` that is a view of the prvate `stream0` field

2022-12-25 23:51 UTC, revol-xut approved these changes

2023-01-02 21:48 UTC, revol-xut commented on src/_core/map/map.component.ts
> +  private readonly location0 = new Subject<Location>();
maybe rename it public_location and private_location for verbosity

2023-01-12 18:51 UTC, revol-xut commented
@MarcelCoding Do want to merge this ?

2023-01-12 21:59 UTC, MarcelCoding commented
Yes but icons

2023-01-12 22:00 UTC, MarcelCoding commented
I need to add all possible shades and improve the tram

2023-01-12 22:16 UTC, merged