Add basic vehicle sidebar
tlm-solutions/windshield pull request #23
Opened 2023-01-27 09:13 UTC by MarcelCoding

2023-01-30 01:11 UTC, revol-xut requested changes

2023-01-30 01:11 UTC, revol-xut commented on src/app/pages/region/region-vehicle-sidebar/region-vehicle-sidebar.component.ts
> +
add the other attributes that a vehicle can have like last seen reporting_point, direction, delay

2023-01-30 01:11 UTC, revol-xut commented on src/app/pages/region/region-vehicle-sidebar/region-vehicle-sidebar.component.ts
> +  protected run: number | undefined;
why are they possible undefined ?

2023-01-30 01:11 UTC, revol-xut commented on src/_core/map/vehicle/bus.ts
> +      id,
do u know use the ids for faster looking up components on the map ?

2023-01-30 01:11 UTC, revol-xut commented on src/_core/map/map.component.ts
> +    this.map.on("click", event => {
is this because u get some map component and then find the corresponding object ?

2023-01-30 01:11 UTC, revol-xut commented on src/_core/map/map.component.ts
> +  private readonly selectedVehicle0 = new Subject<{ line: number, run: number }>();
can we really not name them `selectedVehiclePrivate` ? or do u want to stay with the name because its shorter ?

2023-01-30 18:16 UTC, MarcelCoding commented on src/app/pages/region/region-vehicle-sidebar/region-vehicle-sidebar.component.ts
> +  protected run: number | undefined;
If they can't be found in our pre-defined JSON or the user typed something in the URL that does not exist. In the end, a click on a vehicle is just a change in the URL, so the user could potentially put anything in the URL, even non-existent vehicles.

2023-01-30 18:16 UTC, MarcelCoding commented on src/_core/map/vehicle/bus.ts
> +      id,
I don't quite get what you mean?

2023-01-30 18:17 UTC, MarcelCoding commented on src/_core/map/map.component.ts
> +    this.map.on("click", event => {
I just get the pixels that got clicked, later I use a method to find all "features" that are located at these pixels.

2023-01-30 18:18 UTC, MarcelCoding commented on src/_core/map/map.component.ts
> +  private readonly selectedVehicle0 = new Subject<{ line: number, run: number }>();
idk

2023-02-01 10:12 UTC, revol-xut commented on src/app/pages/region/region-vehicle-sidebar/region-vehicle-sidebar.component.ts
> +
direction tells the traffic light into which direction the tram/bus wants to go (left, right, straight, etc ...)

2023-02-01 10:33 UTC, revol-xut commented on src/_core/map/map.component.ts
> +  private readonly selectedVehicle0 = new Subject<{ line: number, run: number }>();
as long as it is consistent its fine by me

2023-02-10 07:59 UTC, merged